pages:
  stage: deploy
  image: node:6
  script:
    - npm install
    - npm install --global gatsby-cli
    - gatsby build
    - mkdir -p public/.well-known/acme-challenge
    - touch public/.well-known/acme-challenge/h3WphqVlvm2UrrMkIcSUX1SzZua6UaTTXlVS1pgHXX0.html
    - echo "h3WphqVlvm2UrrMkIcSUX1SzZua6UaTTXlVS1pgHXX0.pqp6GrLwC3ZJ_3RZur99eCuXTGDXe7VeXnIhCm7RAFY" > public/.well-known/acme-challenge/h3WphqVlvm2UrrMkIcSUX1SzZua6UaTTXlVS1pgHXX0.html
  artifacts:
    paths:
      - public
  only:
    - master